### ISSUE TITLE
Training fails when `Use_Mixed_Precision` is set to `true`

### ISSUE THREAD

**Issue by 3c1u** [CODEJIN/HiFiSinger#3]
Hi, I'm trying to use HiFISinger with [Tohoku Kiritan](https://zunko.jp/kiridev/login.php); a Japanese singing voice dataset ([repo](https://github.com/3c1u/kiritan_singing/)).

I found that the training with mixed precision seems to fail.

```
[Training]:   0%|                                                                                                                                                   | 0/400000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "Train.py", line 696, in <module>
    new_Trainer.Train()
  File "Train.py", line 656, in Train
    self.Train_Epoch()
  File "Train.py", line 330, in Train_Epoch
    self.Train_Step(durations, tokens, notes, token_lengths, mels, silences, pitches, mel_lengths)
  File "Train.py", line 239, in Train_Step
    scaled_loss.backward()
  File "/home/data/futabanzu/miniconda3/envs/py38/lib/python3.8/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/data/futabanzu/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 130, in backward
    Variable._execution_engine.run_backward(
  File "/home/data/futabanzu/miniconda3/envs/py38/lib/python3.8/site-packages/torch/autograd/function.py", line 89, in apply
    return self._forward_cls.backward(self, *args)  # type: ignore
  File "/home/lab/futabanzu/HIFISinger/thirdparty/HiFiSinger/nvlabs/torch_utils/ops/conv2d_gradfix.py", line 131, in backward
    grad_weight = Conv2dGradWeight.apply(grad_output, input)
  File "/home/lab/futabanzu/HIFISinger/thirdparty/HiFiSinger/nvlabs/torch_utils/ops/conv2d_gradfix.py", line 145, in forward
    grad_weight = op(weight_shape, grad_output, input, padding, stride, dilation, groups, *flags)
RuntimeError: Expected tensor for argument #1 'grad_output' to have the same type as tensor for argument #2 'input'; but type torch.cuda.HalfTensor does not equal torch.cuda.FloatTensor (while checking arguments for cudnn_convolution_backward_weight)
```

**Comment by CODEJIN** [comment]
Sorry for the late reply. It seems that the bug appeared while using NVlabs' Conv_Gradfix to increase the efficiency of the WGAN-GP... I am going to fix it this week, so please wait a little bit.

**Comment by CODEJIN** [comment]
Hi, I fixed the mixed precision problem. Please check it and feedback.

**Comment by 3c1u** [comment]
Thanks, it worked!
